# Update blueprints dependencies
# since these are not managed by projen.
version: 2
updates:
  - package-ecosystem: "npm"
    directories:
      - "/blueprints/*"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "daily"
    groups:
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"