# Main branch only workflow for deploying the Landing Zone Accelerator on AWS config
# TODO: Uncomment this to set up a Continuous Deployment pipeline
#name: Deploy AWS Accelerator Config
#
#on:
#  push:
#    branches:
#      - main
#
#env:
#  AWS_REGION: "eu-central-1"
#
#permissions:
#  id-token: write  # Required for requesting the JWT
#  contents: read   # Required for actions/checkout
#
#jobs:
#  Deploy:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v4
#
#      - name: Use correct node version
#        uses: actions/setup-node@v4
#        with:
#          node-version-file: .node-version
#
#      - name: Install dependencies
#        run: npm ci
#
#      - name: Configure AWS credentials
#        uses: aws-actions/configure-aws-credentials@v4
#        with:
#          role-to-assume: arn:aws:iam::<<AWS_MANAGEMENT_ACCOUNT_ID>>:role/github-actions-role
#          aws-region: ${{ env.AWS_REGION }}
#
#      - name: Deploy aws-accelerator-config
#        run: npm run cli -- deploy
